import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "../globals.css";
import { FaHouseChimney, FaGear } from "react-icons/fa6";
import { FaChalkboardTeacher } from "react-icons/fa";
import { GiGraduateCap } from "react-icons/gi";
import { AuthProvider, useAuth } from "@/context/AuthContext";
// import StyledComponentsRegistry from "../../../lib/AntdRegistry";
import { notFound } from "next/navigation";
import { ReactNode } from "react";
import {
  NextIntlClientProvider,
  useMessages,
  useTranslations,
} from "next-intl";
import { SessionProvider } from "next-auth/react";
import UserLayout from "@/component/UserLayout";

interface RootLayoutProps {
  children: ReactNode;
  params: { locale: string };
}

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LightHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: RootLayoutProps) {
  const messages = useMessages();
  return (
    <html lang={locale}>
      {/* <body className={inter.className}> */}
      <body className="">
        <NextIntlClientProvider locale={locale} messages={messages}>
          <AuthProvider>
            <UserLayout children={children} locale={locale} />
          </AuthProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
