import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import NavBar from "@/component/NavBar";
import Footer from "@/component/Footer";
import Link from "next/link";
import { FaHouseChimney, FaGear } from "react-icons/fa6";
import { FaChalkboardTeacher } from "react-icons/fa";
import { GiGraduateCap } from "react-icons/gi";
import { AuthProvider } from "@/context/AuthContext";
// import StyledComponentsRegistry from "../../../lib/AntdRegistry";
import { notFound } from "next/navigation";
import { ReactNode } from "react";
import {
  NextIntlClientProvider,
  useMessages,
  useTranslations,
} from "next-intl";
import { SessionProvider } from "next-auth/react";
import Providers from "@/component/Providers";

interface RootLayoutProps {
  children: ReactNode;
  params: { locale: string };
}

const locales = ["en", "vi"];

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LightHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: RootLayoutProps) {
  const messages = useMessages();
  const t = useTranslations("Navbar");

  if (!locales.includes(locale as any)) notFound();
  const navigation = [
    { name: `${t("home")}`, href: "/", icon: <FaHouseChimney /> },
    {
      name: `${t("teaching")}`,
      href: "/teaching",
      icon: <FaChalkboardTeacher />,
    },
    { name: `${t("enrolled")}`, href: "/enrolled", icon: <GiGraduateCap /> },
    { name: `${t("setting")}`, href: "/settings", icon: <FaGear /> },
  ];

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <AuthProvider>
            <div
              className="drawer 
            bg-cover bg-repeat bg-[url('https://dbhi.edu.vn/wp-content/uploads/2019/09/white-background-with-blue-tech-hexagon_1017-19366.jpg')]"
            >
              <input id="my-drawer" type="checkbox" className="drawer-toggle" />
              <div className="drawer-content flex flex-col h-screen justify-between">
                <NavBar />
                <main>
                  {/* <StyledComponentsRegistry> */}
                  <Providers>{children}</Providers>
                  {/* </StyledComponentsRegistry> */}
                </main>
                <Footer />
              </div>
              <div className="drawer-side">
                <label
                  htmlFor="my-drawer"
                  aria-label="close sidebar"
                  className="drawer-overlay"
                ></label>

                <ul className="menu p-4 w-80 min-h-full bg-base-200 text-base-content text-lg">
                  {/* Sidebar content here */}
                  <a className="btn btn-ghost normal-case text-xl mb-5">
                    <img
                      className="h-8 w-auto"
                      src="https://bootstraplogos.com/wp-content/uploads/edd/2018/07/logo.png"
                      alt=""
                    ></img>
                    LightHub
                  </a>
                  {navigation.map((item, index) => (
                    <li className="cursor-pointer" key={index}>
                      <Link href={item.href}>
                        <div className="flex w-full">
                          <div className="grid flex-grow place-items-center">
                            {item.icon}
                          </div>
                          <div className="divider divider-horizontal"></div>
                          <div className="grid flex-grow place-items-center">
                            {item.name}
                          </div>
                        </div>
                      </Link>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </AuthProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
